// Global
export const GLOBAL_LOADING_ACTIVE = 'GLOBAL_LOADING_ACTIVE';
export const GLOBAL_LOADING_PASSIVE = 'GLOBAL_LOADING_PASSIVE';

export const REFRESH_TOKEN_POST = 'REFRESH_TOKEN_POST';

// MOVIES
export const DAILY_TRENDING_MOVIES_GET = 'DAILY_TRENDING_MOVIES_GET';
export const WEEKLY_TRENDING_MOVIES_GET = 'WEEKLY_TRENDING_MOVIES_GET';
export const DISCOVER_MOVIES_WITH_GENRE_GET = 'DISCOVER_MOVIES_WITH_GENRE_GET';

// COMMENTS
export const GET_COMMENTS = 'GET_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';