export enum CUSTOM_COLORS {
    WHITE = '#fff',
    BLACK = '#000',
    GREEN = 'green',
    GRAY = 'gray',
    RED = 'red',
    YELLOW = 'yellow',
    MAIN_BACKGROUND_COLOR = '#222222',
    MAIN_TEXT_COLOR = '#f0f0f0',
    MAIN_INPUT_BG_COLOR = '#444',
    SECONDARY_TEXT_COLOR = '#D9d9d9',
    TAB_BAR_ICON_INACTIVE_COLOR = '#555',
    TAB_BAR_ICON_ACTIVE_COLOR = '#fff',
}

export enum CUSTOM_COLORS_TYPE {
    WHITE = 'WHITE',
    BLACK = 'BLACK',
    GREEN = 'GREEN',
    GRAY = 'GRAY',
    RED = 'RED',
    YELLOW = 'YELLOW',
    MAIN_BACKGROUND_COLOR = 'MAIN_BACKGROUND_COLOR',
    MAIN_TEXT_COLOR = 'MAIN_TEXT_COLOR',
    MAIN_INPUT_BG_COLOR = 'MAIN_INPUT_BG_COLOR',
    SECONDARY_TEXT_COLOR = 'SECONDARY_TEXT_COLOR',
    TAB_BAR_ICON_INACTIVE_COLOR = 'TAB_BAR_ICON_INACTIVE_COLOR',
    TAB_BAR_ICON_ACTIVE_COLOR = 'TAB_BAR_ICON_ACTIVE_COLOR',
}

export enum CUSTOM_BG_COLORS_TYPE {
    WHITE_BG = 'WHITE_BG',
    BLACK_BG = 'BLACK_BG',
    GREEN_BG = 'GREEN_BG',
    GRAY_BG = 'GRAY_BG',
    RED_BG = 'RED_BG',
    YELLOW_BG = 'YELLOW_BG',
    MAIN_TEXT_COLOR_BG = 'MAIN_TEXT_COLOR_BG',
    SECONDARY_TEXT_COLOR_BG = 'SECONDARY_TEXT_COLOR_BG',
    TAB_BAR_ICON_INACTIVE_COLOR_BG = 'TAB_BAR_ICON_INACTIVE_COLOR',
    TAB_BAR_ICON_ACTIVE_COLOR_BG = 'TAB_BAR_ICON_ACTIVE_COLOR',
}